package com.jazz_harmony_helper.jazz_harmony_helper_application.harmonic_analysis_driven_chord_set;

import com.jazz_harmony_helper.jazz_harmony_helper_application.chord.ChordAbstract;
import com.jazz_harmony_helper.jazz_harmony_helper_application.chord.ChordQuality;
import com.jazz_harmony_helper.jazz_harmony_helper_application.key.KeyRelativeModality;
import com.jazz_harmony_helper.jazz_harmony_helper_application.scale.Interval;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.SequencedSet;
import java.util.Set;

import static com.jazz_harmony_helper.jazz_harmony_helper_application.scale.Interval.*;

public enum HarmonicAnalysisDrivenChordSetAbstract {
    /*
        Will generate these HarmonicAnalysisDrivenChordSets for Major keys only
     */
    MAJOR_TONIC_MAJOR_SEVENTH(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.MAJOR_SEVENTH_CHORD,
            TONIC,
            HarmonicClassification.DIATONIC,
            HarmonicFunction.TONIC,
            Collections.singletonList(
                    ChordAbstract.GENERAL_MAJOR_SEVENTH
            )
    ),
    MAJOR_TONIC_MAJOR_SIXTH(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.MAJOR_SIXTH_CHORD,
            TONIC,
            HarmonicClassification.DIATONIC,
            HarmonicFunction.TONIC,
            Collections.singletonList(
                    ChordAbstract.GENERAL_MAJOR_SIXTH
            )
    ),
    MAJOR_TWO_MINOR_SEVEN(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.MINOR_SEVENTH_CHORD,
            MAJOR_SECOND,
            HarmonicClassification.DIATONIC,
            HarmonicFunction.SUBDOMINANT,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SEVENTH
            )
    ),
    MAJOR_THREE_MINOR_SEVEN(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.MINOR_SEVENTH_CHORD,
            MAJOR_THIRD,
            HarmonicClassification.DIATONIC,
            HarmonicFunction.TONIC,
            Collections.singletonList(
                    ChordAbstract.GENERAL_PHRYGIAN_MINOR_SEVENTH
            )
    ),
    MAJOR_FOUR_MAJOR_SEVEN(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.MAJOR_SEVENTH_CHORD,
            PERFECT_FOURTH,
            HarmonicClassification.DIATONIC,
            HarmonicFunction.SUBDOMINANT,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SEVENTH
            )
    ),
    MAJOR_FOUR_MAJOR_SIXTH(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.MAJOR_SIXTH_CHORD,
            PERFECT_FOURTH,
            HarmonicClassification.DIATONIC,
            HarmonicFunction.SUBDOMINANT,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SIXTH
            )
    ),
    MAJOR_FIVE_DOMINANT_SEVENTH(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            PERFECT_FIFTH,
            HarmonicClassification.DIATONIC,
            HarmonicFunction.DOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH,
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH_SUS_FOUR,
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET,
                    ChordAbstract.DOMINANT_SEVENTH_SYMMETRIC_DOMINANT,
                    ChordAbstract.DOMINANT_SEVENTH_ALTERED_DOMINANT
            )
    ),
    MAJOR_FIVE_MAJOR_SIXTH(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.MAJOR_SIXTH_CHORD,
            PERFECT_FIFTH,
            HarmonicClassification.DIATONIC,
            HarmonicFunction.DOMINANT,
            Collections.singletonList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_MAJOR_SIXTH
            )
    ),
    MAJOR_SIX_MINOR_SEVENTH(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.MINOR_SEVENTH_CHORD,
            MAJOR_SIXTH,
            HarmonicClassification.DIATONIC,
            HarmonicFunction.TONIC,
            Collections.singletonList(
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_SEVENTH
            )
    ),
    MAJOR_FIVE_OF_FOUR(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            TONIC,
            HarmonicClassification.SECONDARY_DOMINANT,
            HarmonicFunction.SECONDARY_DOMINANT,
            Collections.singletonList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH
            )
    ),
    MAJOR_FIVE_OF_FIVE(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MAJOR_SECOND,
            HarmonicClassification.SECONDARY_DOMINANT,
            HarmonicFunction.SECONDARY_DOMINANT,
            Collections.singletonList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH
            )
    ),
    MAJOR_FIVE_OF_SIX(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MAJOR_THIRD,
            HarmonicClassification.SECONDARY_DOMINANT,
            HarmonicFunction.SECONDARY_DOMINANT,
            Collections.singletonList(
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET
            )
    ),
    MAJOR_FIVE_OF_THREE(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MAJOR_SEVENTH,
            HarmonicClassification.SECONDARY_DOMINANT,
            HarmonicFunction.SECONDARY_DOMINANT,
            Arrays.asList(
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET,
                    ChordAbstract.DOMINANT_SEVENTH_ALTERED_DOMINANT
            )
    ),
    MAJOR_FIVE_OF_TWO(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MAJOR_SIXTH,
            HarmonicClassification.SECONDARY_DOMINANT,
            HarmonicFunction.SECONDARY_DOMINANT,
            Collections.singletonList(
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET
            )
    ),
    MAJOR_TWO_OF_FOUR(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.MINOR_SEVENTH_CHORD,
            PERFECT_FIFTH,
            HarmonicClassification.SECONDARY_PREDOMINANT,
            HarmonicFunction.SECONDARY_PREDOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SEVENTH,
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_SEVENTH
            )
    ),
    MAJOR_TWO_OF_SIX(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.MINOR_SEVENTH_CHORD,
            MAJOR_SEVENTH,
            HarmonicClassification.SECONDARY_PREDOMINANT,
            HarmonicFunction.SECONDARY_PREDOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE,
                    ChordAbstract.GENERAL_PHRYGIAN_MINOR_SEVENTH,
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_SEVENTH
            )
    ),
    MAJOR_TWO_OF_TWO(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.MINOR_SEVENTH_CHORD,
            MAJOR_THIRD,
            HarmonicClassification.SECONDARY_PREDOMINANT,
            HarmonicFunction.SECONDARY_PREDOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_PHRYGIAN_MINOR_SEVENTH,
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_SEVENTH,
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE
            )
    ),
    MAJOR_TWO_OF_THREE(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.MINOR_SEVENTH_CHORD,
            AUGMENTED_FOURTH,
            HarmonicClassification.SECONDARY_PREDOMINANT,
            HarmonicFunction.SECONDARY_PREDOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE,
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_SEVENTH
            )
    ),
    MAJOR_TWO_OF_FIVE(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.MINOR_SEVENTH_CHORD,
            MAJOR_SIXTH,
            HarmonicClassification.SECONDARY_PREDOMINANT,
            HarmonicFunction.SECONDARY_PREDOMINANT,
            Collections.singletonList(
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_SEVENTH
            )
    ),
    MAJOR_SUB_FIVE(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MINOR_SECOND,
            HarmonicClassification.SUBSTITUTE_DOMINANT,
            HarmonicFunction.SECONDARY_DOMINANT,
            Collections.singletonList(
                    ChordAbstract.DOMINANT_SEVENTH_LYDIAN_DOMINANT
            )
    ),
    MAJOR_SUB_FIVE_OF_TWO(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MINOR_THIRD,
            HarmonicClassification.SUBSTITUTE_DOMINANT,
            HarmonicFunction.SECONDARY_DOMINANT,
            Collections.singletonList(
                    ChordAbstract.DOMINANT_SEVENTH_LYDIAN_DOMINANT
            )
    ),
    MAJOR_SUB_FIVE_OF_THREE(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            PERFECT_FOURTH,
            HarmonicClassification.SUBSTITUTE_DOMINANT,
            HarmonicFunction.SECONDARY_DOMINANT,
            Collections.singletonList(
                    ChordAbstract.DOMINANT_SEVENTH_LYDIAN_DOMINANT
            )
    ),
    MAJOR_SUB_FIVE_OF_FOUR(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            DIMINISHED_FIFTH,
            HarmonicClassification.SUBSTITUTE_DOMINANT,
            HarmonicFunction.SECONDARY_DOMINANT,
            Collections.singletonList(
                    ChordAbstract.DOMINANT_SEVENTH_LYDIAN_DOMINANT
            )
    ),
    MAJOR_SUB_FIVE_OF_FIVE(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MINOR_SIXTH,
            HarmonicClassification.SUBSTITUTE_DOMINANT,
            HarmonicFunction.SECONDARY_DOMINANT,
            Collections.singletonList(
                    ChordAbstract.DOMINANT_SEVENTH_LYDIAN_DOMINANT
            )
    ),
    MAJOR_SUB_FIVE_OF_SIX(
            Collections.singletonList(KeyRelativeModality.MAJOR),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MINOR_SEVENTH,
            HarmonicClassification.SUBSTITUTE_DOMINANT,
            HarmonicFunction.SECONDARY_DOMINANT,
            Collections.singletonList(
                    ChordAbstract.DOMINANT_SEVENTH_LYDIAN_DOMINANT
            )
    ),

    /*
     *  Will generate these HarmonicAnalysisDrivenChordSets for Minor keys only
     */


    
    /*
     *  Will generate these HarmonicAnalysisDrivenChordSets for both Major and Minor keys
     */
    
    ALL_SECONDARY_CHAIN_ONE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            TONIC,
            HarmonicClassification.SECONDARY_DOMINANT_CHAIN,
            HarmonicFunction.SECONDARY_DOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH,
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET,
                    ChordAbstract.DOMINANT_SEVENTH_SYMMETRIC_DOMINANT,
                    ChordAbstract.DOMINANT_SEVENTH_ALTERED_DOMINANT,
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH_SUS_FOUR
            )
    ),
    ALL_SECONDARY_CHAIN_FLAT_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MINOR_SECOND,
            HarmonicClassification.SECONDARY_DOMINANT_CHAIN,
            HarmonicFunction.SECONDARY_DOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH,
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET,
                    ChordAbstract.DOMINANT_SEVENTH_SYMMETRIC_DOMINANT,
                    ChordAbstract.DOMINANT_SEVENTH_ALTERED_DOMINANT,
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH_SUS_FOUR
            )
    ),
    ALL_SECONDARY_CHAIN_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MAJOR_SECOND,
            HarmonicClassification.SECONDARY_DOMINANT_CHAIN,
            HarmonicFunction.SECONDARY_DOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH,
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET,
                    ChordAbstract.DOMINANT_SEVENTH_SYMMETRIC_DOMINANT,
                    ChordAbstract.DOMINANT_SEVENTH_ALTERED_DOMINANT,
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH_SUS_FOUR
            )
    ),
    ALL_SECONDARY_CHAIN_FLAT_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MINOR_THIRD,
            HarmonicClassification.SECONDARY_DOMINANT_CHAIN,
            HarmonicFunction.SECONDARY_DOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH,
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET,
                    ChordAbstract.DOMINANT_SEVENTH_SYMMETRIC_DOMINANT,
                    ChordAbstract.DOMINANT_SEVENTH_ALTERED_DOMINANT,
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH_SUS_FOUR
            )
    ),
    ALL_SECONDARY_CHAIN_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MAJOR_THIRD,
            HarmonicClassification.SECONDARY_DOMINANT_CHAIN,
            HarmonicFunction.SECONDARY_DOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH,
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET,
                    ChordAbstract.DOMINANT_SEVENTH_SYMMETRIC_DOMINANT,
                    ChordAbstract.DOMINANT_SEVENTH_ALTERED_DOMINANT,
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH_SUS_FOUR
            )
    ),
    ALL_SECONDARY_CHAIN_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            PERFECT_FOURTH,
            HarmonicClassification.SECONDARY_DOMINANT_CHAIN,
            HarmonicFunction.SECONDARY_DOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH,
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET,
                    ChordAbstract.DOMINANT_SEVENTH_SYMMETRIC_DOMINANT,
                    ChordAbstract.DOMINANT_SEVENTH_ALTERED_DOMINANT,
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH_SUS_FOUR
            )
    ),
    ALL_SECONDARY_CHAIN_SHARP_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            AUGMENTED_FOURTH,
            HarmonicClassification.SECONDARY_DOMINANT_CHAIN,
            HarmonicFunction.SECONDARY_DOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH,
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET,
                    ChordAbstract.DOMINANT_SEVENTH_SYMMETRIC_DOMINANT,
                    ChordAbstract.DOMINANT_SEVENTH_ALTERED_DOMINANT,
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH_SUS_FOUR
            )
    ),
    ALL_SECONDARY_CHAIN_FLAT_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            DIMINISHED_FIFTH,
            HarmonicClassification.SECONDARY_DOMINANT_CHAIN,
            HarmonicFunction.SECONDARY_DOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH,
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET,
                    ChordAbstract.DOMINANT_SEVENTH_SYMMETRIC_DOMINANT,
                    ChordAbstract.DOMINANT_SEVENTH_ALTERED_DOMINANT,
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH_SUS_FOUR
            )
    ),
    ALL_SECONDARY_CHAIN_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            PERFECT_FIFTH,
            HarmonicClassification.SECONDARY_DOMINANT_CHAIN,
            HarmonicFunction.SECONDARY_DOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH,
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET,
                    ChordAbstract.DOMINANT_SEVENTH_SYMMETRIC_DOMINANT,
                    ChordAbstract.DOMINANT_SEVENTH_SYMMETRIC_DOMINANT
            )
    ),
    ALL_SECONDARY_CHAIN_FLAT_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MINOR_SIXTH,
            HarmonicClassification.SECONDARY_DOMINANT_CHAIN,
            HarmonicFunction.SECONDARY_DOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH,
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET,
                    ChordAbstract.DOMINANT_SEVENTH_SYMMETRIC_DOMINANT,
                    ChordAbstract.DOMINANT_SEVENTH_ALTERED_DOMINANT,
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH_SUS_FOUR
            )
    ),
    ALL_SECONDARY_CHAIN_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MAJOR_SIXTH,
            HarmonicClassification.SECONDARY_DOMINANT_CHAIN,
            HarmonicFunction.SECONDARY_DOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH,
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET,
                    ChordAbstract.DOMINANT_SEVENTH_SYMMETRIC_DOMINANT,
                    ChordAbstract.DOMINANT_SEVENTH_ALTERED_DOMINANT,
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH_SUS_FOUR
            )
    ),
    ALL_SECONDARY_CHAIN_FLAT_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MINOR_SEVENTH,
            HarmonicClassification.SECONDARY_DOMINANT_CHAIN,
            HarmonicFunction.SECONDARY_DOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH,
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET,
                    ChordAbstract.DOMINANT_SEVENTH_SYMMETRIC_DOMINANT,
                    ChordAbstract.DOMINANT_SEVENTH_ALTERED_DOMINANT,
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH_SUS_FOUR
            )
    ),
    ALL_SECONDARY_CHAIN_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DOMINANT_SEVENTH_CHORD,
            MAJOR_SEVENTH,
            HarmonicClassification.SECONDARY_DOMINANT_CHAIN,
            HarmonicFunction.SECONDARY_DOMINANT,
            Arrays.asList(
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH,
                    ChordAbstract.DOMINANT_SEVENTH_MINOR_TARGET,
                    ChordAbstract.DOMINANT_SEVENTH_SYMMETRIC_DOMINANT,
                    ChordAbstract.DOMINANT_SEVENTH_ALTERED_DOMINANT,
                    ChordAbstract.GENERAL_MIXOLYDIAN_DOMINANT_SEVENTH_SUS_FOUR
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SEVENTH_ONE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SEVENTH_CHORD,
            TONIC,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SEVENTH_FLAT_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SEVENTH_CHORD,
            MINOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SEVENTH_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SEVENTH_CHORD,
            MAJOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SEVENTH_FLAT_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SEVENTH_CHORD,
            MINOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SEVENTH_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SEVENTH_CHORD,
            MAJOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SEVENTH_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SEVENTH_CHORD,
            PERFECT_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SEVENTH_SHARP_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SEVENTH_CHORD,
            AUGMENTED_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SEVENTH_FLAT_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SEVENTH_CHORD,
            DIMINISHED_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SEVENTH_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SEVENTH_CHORD,
            PERFECT_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SEVENTH_FLAT_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SEVENTH_CHORD,
            MINOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SEVENTH_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SEVENTH_CHORD,
            MAJOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SEVENTH_FLAT_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SEVENTH_CHORD,
            MINOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SEVENTH_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SEVENTH_CHORD,
            MAJOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SIXTH_ONE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SIXTH_CHORD,
            TONIC,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SIXTH_FLAT_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SIXTH_CHORD,
            MINOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SIXTH_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SIXTH_CHORD,
            MAJOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SIXTH_FLAT_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SIXTH_CHORD,
            MINOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SIXTH_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SIXTH_CHORD,
            MAJOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SIXTH_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SIXTH_CHORD,
            PERFECT_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SIXTH_SHARP_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SIXTH_CHORD,
            AUGMENTED_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SIXTH_FLAT_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SIXTH_CHORD,
            DIMINISHED_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SIXTH_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SIXTH_CHORD,
            PERFECT_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SIXTH_FLAT_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SIXTH_CHORD,
            MINOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SIXTH_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SIXTH_CHORD,
            MAJOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SIXTH_FLAT_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SIXTH_CHORD,
            MINOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MAJOR_SIXTH_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MAJOR_SIXTH_CHORD,
            MAJOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LYDIAN_MAJOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_ONE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_CHORD,
            TONIC,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_CHORD
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_FLAT_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_CHORD,
            MINOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_CHORD
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_CHORD,
            MAJOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_CHORD
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_FLAT_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_CHORD,
            MINOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_CHORD
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_CHORD,
            MAJOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_CHORD
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_CHORD,
            PERFECT_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_CHORD
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SHARP_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_CHORD,
            AUGMENTED_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_CHORD
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_FLAT_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_CHORD,
            DIMINISHED_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_CHORD
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_CHORD,
            PERFECT_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_CHORD
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_FLAT_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_CHORD,
            MINOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_CHORD
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_CHORD,
            MAJOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_CHORD
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_FLAT_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_CHORD,
            MINOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_CHORD
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_CHORD,
            MAJOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_AEOLIAN_MINOR_CHORD
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVENTH_ONE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVENTH_CHORD,
            TONIC,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVENTH_FLAT_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVENTH_CHORD,
            MINOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVENTH_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVENTH_CHORD,
            MAJOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVENTH_FLAT_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVENTH_CHORD,
            MINOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVENTH_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVENTH_CHORD,
            MAJOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVENTH_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVENTH_CHORD,
            PERFECT_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVENTH_SHARP_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVENTH_CHORD,
            AUGMENTED_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVENTH_FLAT_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVENTH_CHORD,
            DIMINISHED_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVENTH_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVENTH_CHORD,
            PERFECT_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVENTH_FLAT_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVENTH_CHORD,
            MINOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVENTH_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVENTH_CHORD,
            MAJOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVENTH_FLAT_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVENTH_CHORD,
            MINOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVENTH_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVENTH_CHORD,
            MAJOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SIXTH_ONE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SIXTH_CHORD,
            TONIC,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SIXTH_FLAT_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SIXTH_CHORD,
            MINOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SIXTH_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SIXTH_CHORD,
            MAJOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SIXTH_FLAT_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SIXTH_CHORD,
            MINOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SIXTH_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SIXTH_CHORD,
            MAJOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SIXTH_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SIXTH_CHORD,
            PERFECT_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SIXTH_SHARP_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SIXTH_CHORD,
            AUGMENTED_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SIXTH_FLAT_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SIXTH_CHORD,
            DIMINISHED_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SIXTH_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SIXTH_CHORD,
            PERFECT_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SIXTH_FLAT_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SIXTH_CHORD,
            MINOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SIXTH_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SIXTH_CHORD,
            MAJOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SIXTH_FLAT_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SIXTH_CHORD,
            MINOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SIXTH_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SIXTH_CHORD,
            MAJOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_DORIAN_MINOR_SIXTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVEN_FLAT_FIVE_ONE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVEN_FLAT_FIVE_CHORD,
            TONIC,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVEN_FLAT_FIVE_FLAT_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVEN_FLAT_FIVE_CHORD,
            MINOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVEN_FLAT_FIVE_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVEN_FLAT_FIVE_CHORD,
            MAJOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVEN_FLAT_FIVE_FLAT_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVEN_FLAT_FIVE_CHORD,
            MINOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVEN_FLAT_FIVE_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVEN_FLAT_FIVE_CHORD,
            MAJOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVEN_FLAT_FIVE_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVEN_FLAT_FIVE_CHORD,
            PERFECT_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVEN_FLAT_FIVE_SHARP_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVEN_FLAT_FIVE_CHORD,
            AUGMENTED_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVEN_FLAT_FIVE_FLAT_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVEN_FLAT_FIVE_CHORD,
            DIMINISHED_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVEN_FLAT_FIVE_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVEN_FLAT_FIVE_CHORD,
            PERFECT_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVEN_FLAT_FIVE_FLAT_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVEN_FLAT_FIVE_CHORD,
            MINOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVEN_FLAT_FIVE_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVEN_FLAT_FIVE_CHORD,
            MAJOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVEN_FLAT_FIVE_FLAT_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVEN_FLAT_FIVE_CHORD,
            MINOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE
            )
    ),
    ALL_CONSTANT_STRUCTURE_MINOR_SEVEN_FLAT_FIVE_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.MINOR_SEVEN_FLAT_FIVE_CHORD,
            MAJOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.GENERAL_LOCRIAN_MINOR_SEVEN_FLAT_FIVE
            )
    ),





    ALL_CONSTANT_STRUCTURE_AUGMENTED_MAJOR_SEVENTH_ONE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.AUGMENTED_MAJOR_SEVENTH_CHORD,
            TONIC,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.AUGMENTED_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_AUGMENTED_MAJOR_SEVENTH_FLAT_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.AUGMENTED_MAJOR_SEVENTH_CHORD,
            MINOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.AUGMENTED_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_AUGMENTED_MAJOR_SEVENTH_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.AUGMENTED_MAJOR_SEVENTH_CHORD,
            MAJOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.AUGMENTED_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_AUGMENTED_MAJOR_SEVENTH_FLAT_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.AUGMENTED_MAJOR_SEVENTH_CHORD,
            MINOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.AUGMENTED_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_AUGMENTED_MAJOR_SEVENTH_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.AUGMENTED_MAJOR_SEVENTH_CHORD,
            MAJOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.AUGMENTED_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_AUGMENTED_MAJOR_SEVENTH_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.AUGMENTED_MAJOR_SEVENTH_CHORD,
            PERFECT_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.AUGMENTED_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_AUGMENTED_MAJOR_SEVENTH_SHARP_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.AUGMENTED_MAJOR_SEVENTH_CHORD,
            AUGMENTED_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.AUGMENTED_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_AUGMENTED_MAJOR_SEVENTH_FLAT_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.AUGMENTED_MAJOR_SEVENTH_CHORD,
            DIMINISHED_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.AUGMENTED_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_AUGMENTED_MAJOR_SEVENTH_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.AUGMENTED_MAJOR_SEVENTH_CHORD,
            PERFECT_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.AUGMENTED_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_AUGMENTED_MAJOR_SEVENTH_FLAT_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.AUGMENTED_MAJOR_SEVENTH_CHORD,
            MINOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.AUGMENTED_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_AUGMENTED_MAJOR_SEVENTH_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.AUGMENTED_MAJOR_SEVENTH_CHORD,
            MAJOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.AUGMENTED_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_AUGMENTED_MAJOR_SEVENTH_FLAT_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.AUGMENTED_MAJOR_SEVENTH_CHORD,
            MINOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.AUGMENTED_MAJOR_SEVENTH
            )
    ),
    ALL_CONSTANT_STRUCTURE_AUGMENTED_MAJOR_SEVENTH_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.AUGMENTED_MAJOR_SEVENTH_CHORD,
            MAJOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.AUGMENTED_MAJOR_SEVENTH
            )
    ),



    ALL_DIMINISHED_APPROACH_ONE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DIMINISHED_SEVENTH_CHORD,
            TONIC,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.DIMINISHED_SEVENTH_CHORD
            )
    ),
    ALL_DIMINISHED_APPROACH_FLAT_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DIMINISHED_SEVENTH_CHORD,
            MINOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.DIMINISHED_SEVENTH_CHORD
            )
    ),
    ALL_DIMINISHED_APPROACH_TWO(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DIMINISHED_SEVENTH_CHORD,
            MAJOR_SECOND,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.DIMINISHED_SEVENTH_CHORD
            )
    ),
    ALL_DIMINISHED_APPROACH_FLAT_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DIMINISHED_SEVENTH_CHORD,
            MINOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.DIMINISHED_SEVENTH_CHORD
            )
    ),
    ALL_DIMINISHED_APPROACH_THREE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DIMINISHED_SEVENTH_CHORD,
            MAJOR_THIRD,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.DIMINISHED_SEVENTH_CHORD
            )
    ),
    ALL_DIMINISHED_APPROACH_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DIMINISHED_SEVENTH_CHORD,
            PERFECT_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.DIMINISHED_SEVENTH_CHORD
            )
    ),
    ALL_DIMINISHED_APPROACH_SHARP_FOUR(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DIMINISHED_SEVENTH_CHORD,
            AUGMENTED_FOURTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.DIMINISHED_SEVENTH_CHORD
            )
    ),
    ALL_DIMINISHED_APPROACH_FLAT_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DIMINISHED_SEVENTH_CHORD,
            DIMINISHED_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.DIMINISHED_SEVENTH_CHORD
            )
    ),
    ALL_DIMINISHED_APPROACH_FIVE(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DIMINISHED_SEVENTH_CHORD,
            PERFECT_FIFTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.DIMINISHED_SEVENTH_CHORD
            )
    ),
    ALL_DIMINISHED_APPROACH_FLAT_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DIMINISHED_SEVENTH_CHORD,
            MINOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.DIMINISHED_SEVENTH_CHORD
            )
    ),
    ALL_DIMINISHED_APPROACH_SIX(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DIMINISHED_SEVENTH_CHORD,
            MAJOR_SIXTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.DIMINISHED_SEVENTH_CHORD
            )
    ),
    ALL_DIMINISHED_APPROACH_FLAT_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DIMINISHED_SEVENTH_CHORD,
            MINOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.DIMINISHED_SEVENTH_CHORD
            )
    ),
    ALL_DIMINISHED_APPROACH_SEVEN(
            Arrays.asList(KeyRelativeModality.values()),
            ChordQuality.DIMINISHED_SEVENTH_CHORD,
            MAJOR_SEVENTH,
            HarmonicClassification.CONSTANT_STRUCTURE,
            HarmonicFunction.CONSTANT_STRUCTURE,
            Collections.singletonList(
                    ChordAbstract.DIMINISHED_SEVENTH_CHORD
            )
    ),
    ;

    private final Set<KeyRelativeModality> modalityAvailability;
    private final ChordQuality analyzedQuality;
    private final Interval distanceFromKeyRoot;
    private final HarmonicClassification harmonicClassification;
    private final HarmonicFunction harmonicFunction;
    private final SequencedSet<ChordAbstract> availableChords;

    HarmonicAnalysisDrivenChordSetAbstract(
            List<KeyRelativeModality> modalityAvailability,
            ChordQuality analyzedQuality,
            Interval distanceFromKeyRoot,
            HarmonicClassification harmonicClassification,
            HarmonicFunction harmonicFunction,
            List<ChordAbstract> availableChords
    ) {
        this.modalityAvailability = new HashSet<>(modalityAvailability);
        this.analyzedQuality = analyzedQuality;
        this.distanceFromKeyRoot = distanceFromKeyRoot;
        this.harmonicClassification = harmonicClassification;
        this.harmonicFunction = harmonicFunction;
        this.availableChords = new LinkedHashSet<>(availableChords);
    }

    public Set<KeyRelativeModality> getModalityAvailability() {
        return modalityAvailability;
    }

    public ChordQuality getAnalyzedQuality() {
        return analyzedQuality;
    }

    public Interval getDistanceFromKeyRoot() {
        return distanceFromKeyRoot;
    }

    public HarmonicClassification getHarmonicClassification() {
        return harmonicClassification;
    }

    public HarmonicFunction getHarmonicFunction() {
        return harmonicFunction;
    }

    public SequencedSet<ChordAbstract> getAvailableChords() {
        return availableChords;
    }
}
